REGRESSION 
  /DESCRIPTIVES MEAN STDDEV CORR SIG N 
  /MISSING LISTWISE 
  /STATISTICS COEFF OUTS R ANOVA 
  /CRITERIA=PIN(.05) POUT(.10) 
  /NOORIGIN 
  /DEPENDENT Post 
  /METHOD=BACKWARD Pre 
  /METHOD=BACKWARD A 
  /METHOD=BACKWARD C 
  /METHOD=BACKWARD N.